services:
  agromat-bot:
    build: .
    container_name: agromat-bot
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./user_map.json:/app/user_map.json
    restart: unless-stopped
